export const MENTORS = [
  {
    id: "rita-orji",
    name: "Dr. Rita Orji",
    title: "Full Professor & Canada Research Chair",
    org: "Dalhousie University",
    category: "dalhousie",
    tagline: "Designing tech that empowers people to live healthier lives",
    tags: ["Persuasive Technology", "HCI", "AI for Health", "Digital Wellness"],
    dataPoints: "400+ papers · 11,000+ citations",
    avatar: "RO",
    avatarColor: "bg-emerald-600",
    image: "/avatars/rita-orji.jpg",
    featured: true,
    bio: "Nigerian-Canadian computer scientist. Grew up without access to a computer, graduated top of her class, now a UN AI Scientific Panel member — one of only two Canadians selected. She directs the Persuasive Computing Lab at Dalhousie.",
    education: [
      { year: "2014", text: "PhD Computer Science, University of Saskatchewan (Vanier Scholar)" },
      { year: "2016", text: "Banting Fellow, University of Waterloo" },
      { year: "2017", text: "Assistant Professor, Dalhousie University" },
      { year: "2020", text: "Canada Research Chair in Persuasive Technology" },
      { year: "2026", text: "Appointed to UN AI Scientific Panel" },
    ],
    quotes: [
      "Don't just work hard. Work on things that compound your effort.",
      "Nobody ever feels fully ready. Start anyway. The confidence you're waiting for comes from doing, not from preparing to do.",
      "I want to see underrepresented women, Indigenous peoples and those of colour get involved in developing our world through computing.",
    ],
    keyPapers: [
      "Personalized Persuasive Health Interventions (CHI 2023)",
      "Tailoring Persuasive Strategies to Gamer Types (UMUAI 2018)",
      "The Persuasive Potential of Games for Health (Int. J. HCI)",
    ],
  },
  {
    id: "stan-matwin",
    name: "Prof. Stan Matwin",
    title: "Professor & Former Director, Institute for Big Data Analytics",
    org: "Dalhousie University",
    category: "dalhousie",
    tagline: "Pioneering AI and machine learning for over three decades",
    tags: ["Machine Learning", "Text Mining", "Data Privacy", "NLP"],
    dataPoints: "250+ papers · 10,000+ citations",
    avatar: "SM",
    avatarColor: "bg-blue-700",
    image: "/avatars/stan-matwin.jpg",
    bio: "Polish-Canadian computer scientist and a pioneer in machine learning from imbalanced data. Canada Research Chair (Tier 1) at Dalhousie and Distinguished Professor Emeritus at the University of Ottawa, he founded the Institute for Big Data Analytics in 2013. He received the 2019 CAIAC Lifetime Achievement Award, joining the ranks of Yoshua Bengio and Geoffrey Hinton.",
    education: [
      { year: "1977", text: "PhD Computer Science, Warsaw University, Poland" },
      { year: "1992", text: "Tenured Professor, University of Ottawa (Chair of CS Dept 1989–2003)" },
      { year: "2010", text: "CAIAC Distinguished Service Award; Doctor of Science, Polish Academy of Sciences" },
      { year: "2013", text: "Founded Institute for Big Data Analytics, Dalhousie; Canada Research Chair (Tier 1)" },
      { year: "2019", text: "CAIAC Lifetime Achievement Award" },
    ],
    quotes: [
      "The real challenge in machine learning isn't building bigger models — it's learning reliably from scarce, imbalanced, and sensitive data.",
      "Big data is not just a technical problem. It's a societal one — we have a responsibility to ensure it serves people, not just profits.",
    ],
    keyPapers: [
      "Addressing the Curse of Imbalanced Training Sets: One-Sided Selection (ICML 1997)",
      "Feature Engineering for Text Classification (ICML 1999)",
      "A Crypto-Based Approach to Privacy-Preserving Collaborative Data Mining (ICDMW 2006)",
    ],
  },
  {
    id: "srini-sampalli",
    name: "Dr. Srini Sampalli",
    title: "Professor & 3M National Teaching Fellow",
    org: "Dalhousie University",
    category: "dalhousie",
    tagline: "Award-winning educator shaping the next generation in cybersecurity",
    tags: ["Cybersecurity", "IoT Security", "Teaching Excellence"],
    dataPoints: "150+ grad students supervised",
    avatar: "SS",
    avatarColor: "bg-indigo-600",
    image: "/avatars/srini-sampalli.jpg",
    bio: "Dr. Srinivas (Srini) Sampalli is a Professor and 3M National Teaching Fellow at Dalhousie with over 25 years of teaching and research experience. He earned his Ph.D. from the Indian Institute of Science (IISc), Bengaluru, and directs the MYTech Lab. Students honored him by creating the 'Srini Teaching Award' in his name.",
    education: [
      { year: "1989", text: "PhD, Indian Institute of Science (IISc), Bengaluru" },
      { year: "1993", text: "Joined Dalhousie University, Department of Computer Science" },
      { year: "2000", text: "Students create the 'Srini Teaching Award' in his honor" },
      { year: "2005", text: "Awarded 3M National Teaching Fellowship — Canada's most prestigious teaching honor" },
      { year: "2016", text: "Appointed Vice President (Canada), International Federation of National Teaching Fellows" },
    ],
    quotes: [
      "The answer is usually context. If I can explain it in a way that you can relate to it, you will not forget it.",
      "The basic tenets of teaching are universal — good preparation, energetic delivery, and a caring attitude.",
    ],
    keyPapers: [
      "NFC Technology Security Vulnerabilities and Countermeasures",
      "Hybrid Machine Learning Intrusion Detection for Wireless Sensor Networks",
      "Federated Learning Framework for Intrusion Detection on IoT Networks",
    ],
  },
  {
    id: "jean-fran",
    name: "Jean-François Savard",
    title: "CEO & Co-founder",
    org: "Volta (Halifax Innovation Hub)",
    category: "local",
    tagline: "Building Atlantic Canada's startup ecosystem from the ground up",
    tags: ["Startups", "Venture Building", "Atlantic Tech"],
    dataPoints: "50+ startups mentored",
    avatar: "JF",
    avatarColor: "bg-orange-600",
    image: "/avatars/jean-fran.jpg",
  },
  {
    id: "ulrike-bahr",
    name: "Ulrike Bahr-Gedalia",
    title: "President & CEO",
    org: "Digital Nova Scotia",
    category: "local",
    tagline: "Championing digital transformation across Nova Scotia",
    tags: ["Digital Economy", "Tech Policy", "Women in Tech"],
    dataPoints: "20+ years industry leadership",
    avatar: "UB",
    avatarColor: "bg-pink-600",
    image: "/avatars/ulrike-bahr.jpg",
  },
  {
    id: "satya-nadella",
    name: "Satya Nadella",
    title: "Chairman & CEO",
    org: "Microsoft",
    category: "bigtech",
    tagline: "Transforming one of the world's largest companies through empathy and growth mindset",
    tags: ["Cloud Computing", "AI Strategy", "Leadership", "Growth Mindset"],
    dataPoints: "Based on 3 books · 200+ keynotes",
    avatar: "SN",
    avatarColor: "bg-sky-700",
    image: "/avatars/satya-nadella.jpg",
  },
  {
    id: "jensen-huang",
    name: "Jensen Huang",
    title: "Founder & CEO",
    org: "NVIDIA",
    category: "bigtech",
    tagline: "From dishwasher to leading the AI hardware revolution",
    tags: ["GPU Computing", "AI Infrastructure", "Entrepreneurship"],
    dataPoints: "Based on 150+ talks & interviews",
    avatar: "JH",
    avatarColor: "bg-green-700",
    image: "/avatars/jensen-huang.jpg",
  },
  {
    id: "sundar-pichai",
    name: "Sundar Pichai",
    title: "CEO",
    org: "Google / Alphabet",
    category: "bigtech",
    tagline: "From Chennai to leading the world's most influential tech company",
    tags: ["Search & AI", "Product Leadership", "Scaling Teams"],
    dataPoints: "Based on 100+ public talks",
    avatar: "SP",
    avatarColor: "bg-red-600",
    image: "/avatars/sundar-pichai.jpg",
  },
  {
    id: "elon-musk",
    name: "Elon Musk",
    title: "CEO",
    org: "Tesla / SpaceX / xAI",
    category: "legends",
    tagline: "First-principles thinking to solve civilization-scale problems",
    tags: ["Space", "EVs", "AI", "First Principles"],
    dataPoints: "Based on 500+ interviews & biographies",
    avatar: "EM",
    avatarColor: "bg-gray-800",
    image: "/avatars/elon-musk.jpg",
  },
  {
    id: "warren-buffett",
    name: "Warren Buffett",
    title: "Chairman & CEO",
    org: "Berkshire Hathaway",
    category: "legends",
    tagline: "The Oracle of Omaha — decades of wisdom on investing and life",
    tags: ["Value Investing", "Business Strategy", "Life Philosophy"],
    dataPoints: "Based on 60+ annual letters & biographies",
    avatar: "WB",
    avatarColor: "bg-amber-700",
    image: "/avatars/warren-buffett.jpg",
  },
  {
    id: "sam-altman",
    name: "Sam Altman",
    title: "CEO",
    org: "OpenAI",
    category: "legends",
    tagline: "Navigating the frontier of artificial general intelligence",
    tags: ["AGI", "Startups", "Y Combinator", "AI Safety"],
    dataPoints: "Based on 200+ interviews & blog posts",
    avatar: "SA",
    avatarColor: "bg-teal-700",
    image: "/avatars/sam-altman.jpg",
  },
];

export const CATEGORIES = [
  { id: "all", label: "All Mentors" },
  { id: "dalhousie", label: "Dalhousie Faculty" },
  { id: "local", label: "Local Leaders" },
  { id: "bigtech", label: "Big Tech" },
  { id: "legends", label: "Legends" },
];

export function getMentor(id) {
  return MENTORS.find((m) => m.id === id);
}
